/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Center, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import React, { useEffect, useRef, type RefObject } from "react";
import { useMaterial } from "../../hooks/useMaterial";
import { useScroll } from "../scroll/useScroll";
import { useControls } from "leva";

const lembda = 2.5;

interface HandProps extends React.ComponentProps<"group"> {
  mouse: RefObject<{
    x: number;
    y: number;
  }>;
  color: string;
}

export function Arm1(props: HandProps) {
  const { scene } = useGLTF("/models/fixedarm.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, 0, 0);

  const { maxRotation } = useMaterial(scene, props.color);

  const scroll = useScroll();

  useEffect(() => {
    const handleUpdate = (data: {
      progress: number;
      current: number;
      target: number;
    }) => {
      baseRotation.y = data.progress * Math.PI * 2;
    };
    scroll.on("update", handleUpdate);
    return () => {
      scroll.off("update", handleUpdate);
    };
  }, [scroll, baseRotation]);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} position={[0, 10, -2]} scale={0.7} {...props}>
      {/* <Center> */}
      <primitive object={scene} />
      {/* </Center> */}
    </group>
  );
}

export function Arm2(props: HandProps) {
  const { scene } = useGLTF("/models/arm2.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, 0.3, 0);

  const { maxRotation } = useMaterial(scene, props.color);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group scale={0.65} ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

export function Hand1(props: HandProps) {
  const { scene, animations } = useGLTF("/models/actionhand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(2.2, 0, 0);

  const { maxRotation } = useMaterial(scene, props.color);

  const { actions } = useAnimations(animations, groupRef);

  const scroll = useScroll();
  const base = "kulack";
  const sequence = ["One", "Rock_finger", "Three"];

  //       "Fuck",
  //       "GrabHold",
  //       "GrabRelease",
  //       "kulack",
  //       "One",
  //       "Peace_finger",
  //       "Rock_finger",
  //       "Three",

  useEffect(() => {
    [...sequence, base].forEach((name) => {
      const action = actions[name];
      if (action) {
        action.reset();
        action.play();

        action.paused = false;
        action.enabled = true;

        action.setLoop(THREE.LoopRepeat, Infinity);

        // 👇 KEY
        action.setEffectiveWeight(name === base ? 1 : 0);
      }
    });
  }, [actions]);
  useEffect(() => {
    const handleUpdate = (data: { progress: number }) => {
      const p = data.progress;

      // Split progress into two phases:
      // [0, 0.3] = base hold + base→first blend
      // [0.3, 0.7] = sequence blends
      const BASE_END = 0.3;
      const SEQ_END = 0.7;

      const count = sequence.length;
      const blendStart = 0.2;
      const blendEnd = 0.8;

      // Reset all weights
      Object.values(actions).forEach((a) => a?.setEffectiveWeight(0));

      const baseAction = actions[base];
      const firstAction = actions[sequence[0]];

      // Phase 1: pure base or base→first blend
      if (p < BASE_END) {
        const localT = p / BASE_END; // 0→1 over this phase

        if (localT < blendStart) {
          baseAction?.setEffectiveWeight(1);
          return;
        }

        const t = THREE.MathUtils.smootherstep(localT, blendStart, blendEnd);
        baseAction?.setEffectiveWeight(1 - t);
        firstAction?.setEffectiveWeight(t);
        if (firstAction) firstAction.time = firstAction.getClip().duration * t;
        return;
      }

      // Phase 2: sequence blends
      const globalT = THREE.MathUtils.clamp(
        (p - BASE_END) / (SEQ_END - BASE_END),
        0,
        0.999,
      );
      const segmentSize = 1 / count;
      const rawIndex = globalT / segmentSize;
      const index = Math.floor(rawIndex);
      const localT = rawIndex - index;

      const currName = sequence[index];
      const nextName = sequence[index + 1];
      const curr = actions[currName];
      const next = actions[nextName];

      // Last segment
      if (!next) {
        curr?.setEffectiveWeight(1);
        return;
      }

      // Hold current
      if (localT < blendStart) {
        curr?.setEffectiveWeight(1);
        return;
      }

      // Blend
      if (localT <= blendEnd) {
        const t = THREE.MathUtils.smootherstep(localT, blendStart, blendEnd);
        curr?.setEffectiveWeight(1 - t);
        next?.setEffectiveWeight(t);
        next.time = next.getClip().duration * t;
        return;
      }

      // After blend
      next?.setEffectiveWeight(1);
    };

    scroll.on("update", handleUpdate);
    return () => scroll.off("update", handleUpdate);
  }, [scroll, actions]);

  // 🌀 your existing mouse rotation
  useFrame((_, delta) => {
    if (!groupRef.current) return;

    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    groupRef.current.rotation.x =
      baseRotation.x + rotationRef.current.x * maxRotation;
  });

  return (
    <group position={[-0.3, 0, 0]}>
      <group ref={groupRef} scale={1.2} {...props}>
        <primitive object={scene} />
      </group>
    </group>
  );
}

export function Hand2(props: HandProps) {
  const { scene, animations } = useGLTF("/models/use/hand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(Math.PI, 0, -Math.PI / 2);

  const { maxRotation } = useMaterial(scene, props.color);

  const { actions } = useAnimations(animations, groupRef);

  // const { animation } = useControls({
  //   animation: {
  //     value: "Fuck",
  //     options: [
  //       "Fuck",
  //       "GrabHold",
  //       "GrabRelease",
  //       "kulack",
  //       "One",
  //       "Peace_finger",
  //       "Rock_finger",
  //       "Three",
  //     ],
  //   },
  //   rotationX: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  //   rotationY: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  //   rotationZ: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  // },{
  //   collapsed:true
  // });

  // useEffect(() => {
  //   actions[animation]?.reset()
  //   actions[animation]?.fadeIn(.3);
  //   actions[animation]?.play();

  //   return () => {
  //     actions[animation]?.reset();
  //   };
  // }, [actions, animation]);

  useEffect(() => {
    const action = actions["GrabHold"];
    if (action) {
      action.play();
      // action.paused = true; // 👈 important for scroll control
    }
  }, [actions]);

  const scroll = useScroll();

  useEffect(() => {
    const handleUpdate = (data: {
      progress: number;
      current: number;
      target: number;
    }) => {
      const p = data.progress;

      return;

      // 🎯 remap 0.3 → 0 and 0.7 → 1
      const t = THREE.MathUtils.clamp((p - 0.3) / 0.4, 0, 1);

      // 🕹️ play animation based on t
      const action = actions["GrabHold"]; // change to your animation

      if (action) {
        action.paused = false;
        action.enabled = true;
        // action.timeScale = t;

        // console.log(t)

        // ⏱️ scrub animation
        // action.time = action.getClip().duration * t;
      }
    };

    scroll.on("update", handleUpdate);
    return () => {
      scroll.off("update", handleUpdate);
    };
  }, [scroll, actions]);
  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + (rotationRef.current.x * maxRotation) / 3;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.2;
  });

  return (
    <group
      scale={2.2}
      {...props}
      rotation={baseRotation}
      position={[-0.8, 0, 0]}
      ref={groupRef}
    >
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload([
  "/models/arm.glb",
  "/models/arm2.glb",
  "/models/actionhand.glb",
  "/models/The Hand 3D Model.glb",
]);
