/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Center, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import React, { useEffect, useRef, type RefObject } from "react";
import { useMaterial } from "../../hooks/useMaterial";
import { useScroll } from "../scroll/useScroll";
import { useControls } from "leva";

const lembda = 2.5;

interface HandProps extends React.ComponentProps<"group"> {
  mouse: RefObject<{
    x: number;
    y: number;
  }>;
  color: string;
}

export function Arm1(props: HandProps) {
  const { scene } = useGLTF("/models/fixedarm.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, 0, 0);

  const { maxRotation } = useMaterial(scene,props.color);

  const scroll = useScroll();

  useEffect(() => {
    const handleUpdate = (data: {
      progress: number;
      current: number;
      target: number;
    }) => {
      baseRotation.y = data.progress * Math.PI * 2;
    };
    scroll.on("update", handleUpdate);
    return () => {
      scroll.off("update", handleUpdate);
    };
  }, [scroll, baseRotation]);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} position={[0, 10, -2]} scale={0.7} {...props}>
      {/* <Center> */}
      <primitive object={scene} />
      {/* </Center> */}
    </group>
  );
}

export function Arm2(props: HandProps) {
  const { scene } = useGLTF("/models/arm2.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, 0.3, 0);

  const { maxRotation } = useMaterial(scene,props.color);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group scale={0.65} ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

export function Hand1(props: HandProps) {
  const { scene } = useGLTF("/models/actionhand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, Math.PI * 0.2, 0);

  const { maxRotation } = useMaterial(scene,props.color);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

export function Hand2(props: HandProps) {
  const { scene, animations } = useGLTF("/models/use/hand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(Math.PI, 0,-Math.PI / 2);

  const { maxRotation } = useMaterial(scene,props.color);

  const { actions } = useAnimations(animations, groupRef);

  // const { animation } = useControls({
  //   animation: {
  //     value: "Fuck",
  //     options: [
  //       "Fuck",
  //       "GrabHold",
  //       "GrabRelease",
  //       "kulack",
  //       "One",
  //       "Peace_finger",
  //       "Rock_finger",
  //       "Three",
  //     ],
  //   },
  //   rotationX: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  //   rotationY: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  //   rotationZ: {
  //     value: 0,
  //     min: -Math.PI,
  //     max: Math.PI,
  //     step:.001
  //   },
  // },{
  //   collapsed:true
  // });

  // useEffect(() => {
  //   actions[animation]?.reset()
  //   actions[animation]?.fadeIn(.3);
  //   actions[animation]?.play();

  //   return () => {
  //     actions[animation]?.reset();
  //   };
  // }, [actions, animation]);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + (rotationRef.current.x * maxRotation) / 3;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.2;
  });

  return (
    <group
      rotation={baseRotation}
      position={[-.8, 0, 0]}
      scale={2.2}
      ref={groupRef}
      {...props}
    >
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload([
  "/models/arm1.glb",
  "/models/arm2.glb",
  "/models/actionhand.glb",
  "/models/The Hand 3D Model.glb",
]);
