/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Center, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import type { GLTF } from "three-stdlib";
import * as THREE from "three";
import React, { useEffect, useRef, type RefObject } from "react";
import { useControls } from "leva";
import { useMaterial } from "../../hooks/useMaterial";
import { useScroll } from "../scroll/useScroll";

const lembda = 1;

interface HandProps extends React.ComponentProps<"group"> {
  mouse: RefObject<{
    x: number;
    y: number;
  }>;
}

export function Arm1(props: HandProps) {
  const { scene } = useGLTF("/models/fixedarm.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, 0, 0);

  const { maxRotation } = useMaterial(scene);

  const scroll =  useScroll();

  useEffect(() => {
    const handleUpdate = (data: {
      progress: number;
      current: number;
      target: number;
    }) => {
      baseRotation.y = data.progress * Math.PI * 2;
    };
    scroll.on("update", handleUpdate);
    return () => {
      scroll.off("update", handleUpdate);
    };
  }, [scroll,baseRotation]);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} position={[0, 8, -2]} scale={0.8} {...props}>
      {/* <Center> */}
        <primitive object={scene} />
      {/* </Center> */}
    </group>
  );
}

export function Arm2(props: HandProps) {
  const { scene } = useGLTF("/models/arm2.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, .3, 0);

  const { maxRotation } = useMaterial(scene);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group scale={.65} ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

export function Hand1(props: HandProps) {
 const { scene } = useGLTF("/models/actionhand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, Math.PI * .2, 0);

  const { maxRotation } = useMaterial(scene);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

export function Hand2(props: HandProps) {
 const { scene } = useGLTF("/models/the_hand.glb");

  const groupRef = useRef<THREE.Group>(null!);
  const rotationRef = useRef({ x: 0, y: 0 });

  const baseRotation = new THREE.Euler(0, -Math.PI * .2, 0);

  const { maxRotation } = useMaterial(scene);

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    // 🧠 smooth values (store outside if not already)
    rotationRef.current.x = THREE.MathUtils.damp(
      rotationRef.current.x,
      props.mouse.current.x,
      lembda,
      delta,
    );

    rotationRef.current.y = THREE.MathUtils.damp(
      rotationRef.current.y,
      props.mouse.current.y,
      lembda,
      delta,
    );

    // 🎯 apply rotation (base + mouse)
    groupRef.current.rotation.y =
      baseRotation.y + rotationRef.current.x * maxRotation;

    // groupRef.current.rotation.x =
    //   baseRotation.x + rotationRef.current.y * maxRotation * 0.5;
  });

  return (
    <group ref={groupRef} {...props}>
      <Center>
        <primitive object={scene} />
      </Center>
    </group>
  );
}

useGLTF.preload([
  "/models/arm1.glb",
  "/models/arm2.glb",
  "/models/actionhand.glb",
  "/models/The Hand 3D Model.glb",
]);
