/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useBounds, useCubeTexture, useTexture } from "@react-three/drei";
import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Point_Std_Skin_Arm_0: THREE.Mesh
  }
}

export function Hand(props: React.ComponentProps<'group'>) {
  const { nodes } = useGLTF('/models/arm2.glb') as unknown as GLTFResult

  // const [env] = useTexture(['/env.jpg'])


  useEffect(() => {
    

    console.log(nodes['Point_Std_Skin_Arm_0'].material)
  
    return () => {
      
    }
  }, [nodes])
  

  const {
    color,
    metalness,
    roughness
  } = useControls("Hand Material", {
    color: { value: "#0029ff" },
    metalness: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.4, min: 0, max: 1, step: 0.01 },
  },{
    collapsed:true
  });

  useEffect(() => {
    
    if(nodes['Point_Std_Skin_Arm_0']?.material as THREE.MeshStandardMaterial) {
      nodes['Point_Std_Skin_Arm_0'].material.color = new THREE.Color(color)
      nodes['Point_Std_Skin_Arm_0'].material.metalness = metalness
      nodes['Point_Std_Skin_Arm_0'].material.roughness = roughness
    }
  
    return () => {
      
    }
  }, [color,metalness,roughness])
  

  return (
    <group {...props} dispose={null}>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Point_Std_Skin_Arm_0.geometry}
        // material={nodes.Point_Std_Skin_Arm_0.material}
      >
        <meshPhysicalMaterial
              color={color}
              metalness={metalness}
              roughness={roughness}
            />
      </mesh> */}
      <mesh geometry={nodes['Point_Std_Skin_Arm_0'].geometry} material={nodes['Point_Std_Skin_Arm_0'].material} />
    </group>
  )
}

useTexture.preload(['/env.jpg'])

useGLTF.preload('/models/arm2.glb')