/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import type { GLTF } from "three-stdlib";
import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Point_Std_Skin_Arm_0: THREE.Mesh;
  };
};

export function Hand(props: React.ComponentProps<"group">) {
  const { nodes } = useGLTF("/models/arm2.glb") as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null!);
  const isInside = useRef(true);

  // 🎛️ Material Controls
  const { color, metalness, roughness, maxRotation } = useControls(
    "Hand Controls",
    {
      color: { value: "#0029ff" },
      metalness: { value: 0.88, min: 0, max: 1, step: 0.01 },
      roughness: { value: 0.5, min: 0, max: 1, step: 0.01 },

      // 👇 rotation control
      maxRotation: { value: 0.3, min: 0, max: 2, step: 0.01 },
    },
    { collapsed: true },
  );

  // 🎨 Apply material updates
  useEffect(() => {
    const mat = nodes["Point_Std_Skin_Arm_0"]
      .material as THREE.MeshStandardMaterial;

    if (!mat) return;

    mat.color.set(color);
    mat.metalness = metalness;
    mat.roughness = roughness;
  }, [color, metalness, roughness, nodes]);

  // 🖱️ Mouse rotation
  const target = useRef(new THREE.Vector2());
  const current = useRef(new THREE.Vector2());

  useFrame((state) => {
    if (!groupRef.current) return;

    if (isInside.current) {
      target.current.set(state.mouse.x, state.mouse.y);
    } else {
      // 👇 smoothly go back to center
      target.current.set(0, 0);
    }

    current.current.lerp(target.current, 0.04);

    groupRef.current.rotation.y = current.current.x * maxRotation;
    groupRef.current.rotation.x = current.current.y * maxRotation * 0;
  });
  useEffect(() => {
    const canvas = document.querySelector("canvas");

    if (!canvas) return;

    const handleLeave = () => {
      isInside.current = false;
    };

    const handleEnter = () => {
      isInside.current = true;
    };

    canvas.addEventListener("mouseleave", handleLeave);
    canvas.addEventListener("mouseenter", handleEnter);

    return () => {
      canvas.removeEventListener("mouseleave", handleLeave);
      canvas.removeEventListener("mouseenter", handleEnter);
    };
  }, []);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes["Point_Std_Skin_Arm_0"].geometry}
        material={nodes["Point_Std_Skin_Arm_0"].material}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/arm2.glb");
