/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useBounds, useCubeTexture, useTexture } from "@react-three/drei";
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Point_Std_Skin_Arm_0: THREE.Mesh
  }
}

export function Hand(props: React.ComponentProps<'group'>) {
  const { nodes } = useGLTF('/models/arm2.glb') as unknown as GLTFResult

  // const [env] = useTexture(['/env.jpg'])

  const {
    color,
    metalness,
    roughness,
    clearcoat,
    clearcoatRoughness,
    transmission,
    reflectivity,
    envMapIntensity,
    specularIntensity,
    specularColor,
    sheenColor,
    sheen,
    attenuationColor,
    attenuationDistance,
  } = useControls("Hand Material", {
    color: { value: "#aaccff" },
    metalness: { value: .67, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0, min: 0, max: 1, step: 0.01 },
    clearcoat: { value: 0, min: 0, max: 1, step: 0.01 },
    clearcoatRoughness: { value: 0.5, min: 0, max: 1, step: 0.01 },
    transmission: { value: 0, min: 0, max: 1, step: 0.01 },
    reflectivity: { value: 0, min: 0, max: 1, step: 0.01 },
    envMapIntensity: { value: 0, min: 0, max: 10, step: 0.1 },
    specularIntensity: { value: 0, min: 0, max: 5, step: 0.01 },
    specularColor: { value: "#000000" },
    sheenColor: { value: "#001d9f" },
    sheen: { value: 0.6, min: 0, max: 1, step: 0.01 },
    attenuationColor: { value: "#000000" },
    attenuationDistance: { value: 2, min: 0, max: 10, step: 0.01 },
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Point_Std_Skin_Arm_0.geometry}
        // material={nodes.Point_Std_Skin_Arm_0.material}
      >
        <meshPhysicalMaterial
              // envMap={env}
              // color={color}
              color={'blue'}
              metalness={metalness}
              roughness={roughness}
              // clearcoat={clearcoat}
              // clearcoatRoughness={clearcoatRoughness}
              // transmission={transmission}
              // reflectivity={reflectivity}
              // envMapIntensity={envMapIntensity}
              // specularIntensity={specularIntensity}
              // specularColor={specularColor}
              // sheenColor={sheenColor}
              // sheen={sheen}
              // attenuationColor={attenuationColor}
              // attenuationDistance={attenuationDistance}
            />
      </mesh>
    </group>
  )
}

useTexture.preload(['/env.jpg'])

useGLTF.preload('/models/arm2.glb')